name: poker-base
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Santiago Weight
github: santiweight/Exploit
license: BSD3
description: Please see the README on GitHub at <https://github.com/githubuser/Exploit#readme>
copyright: 2019 Santiago Weight
maintainer: santiago.weight@gmail.com

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall

tests:
  test:
    source-dirs:
    - test
    main: Driver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poker-base

dependencies:
- safe-money
- lattices
- base
- aeson
- containers
- deriving-compat
- generic-arbitrary
- lens
- prettyprinter
- QuickCheck
- range
- tasty
- tasty-discover
- tasty-hspec
- tasty-quickcheck
- time
- text
default-extensions:
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- GADTs
- LambdaCase
- LiberalTypeSynonyms
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeOperators
- TypeFamilies
- UnicodeSyntax
- TemplateHaskell